[2주차] 모던자바스크립트 딥다이브 12장
DevoceanDeepDive/Modern-JavaScript pull request #7
Opened 2024-08-05 20:21 UTC by juwonleee

12.1 함수란? 
12.2 함수를 사용하는 이유 
12.3 함수 리터럴 
12.4 함수 정의  
        12.4.1 함수 선언문 
        12.4.2 함수 표현식 
        12.4.3 함수 생성 시점과 함수 호이스팅 
        12.4.4 Function 생성자 함수 
        12.4.5 화살표 함수(ES6) 
12.5 함수 호출 
        12.5.1 매개변수와 인수 
        12.5.2 인수 확인  
        12.5.3 매개변수의 최대 개수  
        12.5.4 반환문  
12.6 참조에 의한 전달과 외부 상태의 변경   
12.7 다양한 함수의 형태 
        12.7.1 즉시 실행 함수 
        12.7.2 재귀 함수 
        12.7.3 중첩 함수 
        12.7.4 콜백 함수 
        12.7.5 순수 함수와 비순수 함수

2024-08-06 14:38 UTC, minseong0324 commented
즉시 실행 함수는 정의와 동시에 즉시 호출되며, 단 한 번만 호출되는데, 이러한 함수가 언제 어떻게 사용되며, 어떤 장점이 있는지 구체적인 예시와 함께 알고 싶어요!

2024-08-06 14:55 UTC, SayisMe commented
[commit 604c749](https://github.com/DevoceanDeepDive/Modern-JavaScript/commit/604c7497ed64a960a6d35f90faaf3d27897c0c4b?diff=unified&w=0) 
main브랜치에 커밋하셨군요 ㅎㅎ
주원님 코드에 필요한 png파일들이 메인 브랜치에 남아있어서, @minseong0324 님이 커밋하실 때 충돌이 발생한 원인으로 작용한 게 아닐까 싶습니다.
- 확인 후 개선해주세요~!
- 코멘트는 여기가 아니라 커밋 내역에다가 달았습니다!

긴 내용인데 수고 많으셨습니다 👍🏻

2024-08-06 15:11 UTC, SayisMe requested changes
[commit 604c749](https://github.com/DevoceanDeepDive/Modern-JavaScript/commit/604c7497ed64a960a6d35f90faaf3d27897c0c4b?diff=unified&w=0) 
main브랜치에 커밋하셨군요 ㅎㅎ
주원님 코드에 필요한 png파일들이 메인 브랜치에 남아있어서, @minseong0324 님이 커밋하실 때 충돌이 발생한 원인으로 작용한 게 아닐까 싶습니다.
- 확인 후 개선해주세요~!
- 코멘트는 여기가 아니라 커밋 내역에다가 달았습니다!

긴 내용인데 수고 많으셨습니다 👍🏻

2024-08-07 05:15 UTC, clicelee commented
거의 700줄이네요 수고 많으셨습니다
질문은 코드에 직접 코멘트로 달았는데 여기에도 적어두겠습니다:
자바스크립트의 setTimeout 함수는 콜백 함수를 비동기적으로 실행한다고 했는데, 이런 비동기 처리가 필요한 경우와 이를 활용한 비동기 프로그래밍의 장점에 대해 구체적인 예시와 함께 설명해 주세요!

2024-08-11 15:30 UTC, juwonleee commented
<aside>
❓ 이로 인해 발생하게될 문제가 뭐가 있을까요?

**보안 문제**

Function 생성자 함수는 문자열을 코드로 평가하기 때문에, 동적 코드 실행을 허용하게 됨. 이는 보안 취약점을 초래할 수 있으며, 특히 사용자 입력을 통해 전달된 문자열이 실행될 경우 위험함.

**디버깅의 어려움**

Function 생성자로 생성된 함수는 일반적으로 코드가 명확하지 않기 때문에 디버깅이 어려울 수 있습니다. 코드가 문자열로 작성되어 있기 때문에, 에러 메시지나 스택 트레이스가 불명확할 수 있습니다.

**성능 저하**

Function 생성자 함수는 새로운 함수를 동적으로 생성할 때마다 문자열을 평가하고 함수를 생성해야 함. 이는 자바스크립트 엔진에 추가적인 오버헤드를 발생시키며, 반복적으로 사용될 경우 성능에 영향을 미칠 수 있음.

</aside>

2024-08-11 15:33 UTC, juwonleee commented
@SayisMe 커밋 revert 해서 고쳐봤습니다! 확인 부탁드려용🙏 확인 후 풀리퀘하겠습니다:)

2024-08-12 00:49 UTC, SayisMe approved these changes

2024-08-12 05:07 UTC, merged