[2주차] 모던자바스크립트 딥다이브 13장
DevoceanDeepDive/Modern-JavaScript pull request #9
Opened 2024-08-06 03:24 UTC by minseong0324

스코프(scope, 유효범위)는 자바스크립트를 포함한 모든 프로그래밍 언어의 기본적이며 중요한 개념이다.
스코프는 함수와 변수에 연관이 깊어서 매우 중요한 개념이니 잘 이해해야한다.
타 언어와 다른 자바스크립트 스코프만의 특징이 존재함으로 이 부분도 주의 깊게 살펴봐야한다.

2024-08-06 15:07 UTC, SayisMe commented
[commit 81aee12](https://github.com/DevoceanDeepDive/Modern-JavaScript/commit/81aee12121316037d5ee9c4e51bab51096117236) 
주원님과 마찬가지로 main브랜치에 커밋하셨습니다.
따라서 @juwonleee 님의 main브랜치 커밋내역과 충돌이 발생한 것 같습니다.
- 확인 후 개선해주세요~!
- 코멘트는 여기가 아니라 커밋 내역에다가 달았습니다!

수고 많으셨습니다. 충돌 해결로 커밋해주셨는데, 아직 conflict 나는걸로 확인되어서 resolve 해야할 것 같습니다.

2024-08-06 15:10 UTC, SayisMe requested changes
[commit 81aee12](https://github.com/DevoceanDeepDive/Modern-JavaScript/commit/81aee12121316037d5ee9c4e51bab51096117236) 
주원님과 마찬가지로 main브랜치에 커밋하셨습니다.
따라서 @juwonleee 님의 main브랜치 커밋내역과 충돌이 발생한 것 같습니다.
- 확인 후 개선해주세요~!
- 코멘트는 여기가 아니라 커밋 내역에다가 달았습니다!

수고 많으셨습니다. 충돌 해결로 커밋해주셨는데, 아직 conflict 나는걸로 확인되어서 resolve 해야할 것 같습니다.

2024-08-07 05:21 UTC, clicelee approved these changes

2024-08-07 05:21 UTC, clicelee commented on minseong0324/chapter13.md
>  블록 레벨 스코프를 지원하는 프로그래밍 언어에서는 for문이 별도의 스코프기 때문에 이런 중복이 일어나지 않는다.
자바스크립트에서 함수 레벨 스코프가 가지는 한계점과 문제점을 예시와 함께 설명해 주세요. 특히, 블록 레벨 스코프를 사용하는 다른 언어들과 비교했을 때의 차이점을 알고 싶어요!

2024-08-07 05:53 UTC, juwonleee commented
**렉시컬 스코프와 동적 스코프**의 차이를 좀 더 구체적으로 알고 싶어요. 특히 예시로 든 코드에서 왜 자바스크립트는 렉시컬 스코프를 사용해서 1이 출력되는지 궁금해요.

왜 var 키워드는 함수 레벨 스코프를 따르는지, 그리고 let이나 const 키워드를 사용하면 어떻게 달라지는지도 궁금해요.

2024-08-11 15:59 UTC, closed without merging